version: 2.1

jobs:
  prepare_dev:
    machine: true
    resource_class: dothanhhau/sematic_search  # Kiểm tra lại resource class này
    environment:
      WORK_DIR: /home/circleci/nckh2025_<< pipeline.git.branch >>_pre
      WORK_DIR2: /home/circleci/nckh2025_<< pipeline.git.branch >>_main
    working_directory: /home/circleci/semantic_search/
    steps:
      - checkout
      - run:
          name: Thiết lập môi trường Python
          shell: /bin/bash
          command: |
            echo "Current directory: $PWD"
            if [ -f .env ]; then rm .env; fi
            # Thiết lập biến môi trường vào file .env
            echo "VNCORE=$VNCORE" >> .env
            echo "PHO_BERT=$PHO_BERT" >> .env
            echo "TESSERACT=$TESSERACT" >> .env
            echo "URL_MILVUS=$URL_MILVUS" >> .env
            echo "POPPLER_PDF=$POPPLER_PDF" >> .env
            echo "TOKEN_MILVUS=$TOKEN_MILVUS" >> .env
            echo "UPLOAD_FOLDER=$UPLOAD_FOLDER" >> .env

            old_requirements=${WORK_DIR}/requirements.txt
            new_requirements=requirements.txt

            # Tạo và kích hoạt môi trường ảo Python

            if cmp -s ${old_requirements} ${new_requirements}; then
              echo 'Tái sử dụng thư viện từ workspace cũ'
              mv ${WORK_DIR}/venv ./venv
              source venv/bin/activate
            else
              echo 'Cài đặt từ requirements.txt mới'
              python3 -m venv venv
              source venv/bin/activate
              pip install -r requirements.txt
            fi
            
            # Dọn dẹp workspace cũ
            if [ -d "${WORK_DIR}" ]; then rm -Rf ${WORK_DIR}; fi
            if [ -d "${WORK_DIR2}" ]; then rm -Rf ${WORK_DIR2}; fi
            mkdir $WORK_DIR
            mkdir $WORK_DIR2
            shopt -s dotglob
            rsync -a . $WORK_DIR
            rsync -a . $WORK_DIR2

            cd $WORK_DIR2
            source venv/bin/activate
            
            # Chạy ứng dụng với Gunicorn
            # gunicorn -b 0.0.0.0:8000 run:app # Kiểm tra lại đường dẫn và ứng dụng

workflows:
  deploy-to-ec2:
    jobs:
      - prepare_dev:
          filters:
            branches:
              only:
                - main
