version: 2.1

jobs:
  prepare_dev:
    machine: true
    resource_class: dothanhhau/sematic_search  # Kiểm tra lại resource class này
    environment:
      WORK_DIR: /home/circleci/nckh2025_<< pipeline.git.branch >>_pre
      WORK_DIR2: /home/circleci/nckh2025_<< pipeline.git.branch >>_main
    working_directory: /home/circleci/semantic_search/
    steps:
      - checkout
      - run:
          name: Thiết lập môi trường Python
          shell: /bin/bash
          command: |
            echo "Current directory: $PWD"
            if [ -f .env ]; then rm .env; fi
            # Thiết lập biến môi trường vào file .env
            echo "VNCORE=$VNCORE" >> .env
            echo "PHO_BERT=$PHO_BERT" >> .env
            echo "TESSERACT=$TESSERACT" >> .env
            echo "URL_MILVUS=$URL_MILVUS" >> .env
            echo "POPPLER_PDF=$POPPLER_PDF" >> .env
            echo "TOKEN_MILVUS=$TOKEN_MILVUS" >> .env
            echo "UPLOAD_FOLDER=$UPLOAD_FOLDER" >> .env

            if [ ! -d "${WORK_DIR}" ]; then
              mkdir -p ${WORK_DIR}
            fi

            old_requirements=${WORK_DIR}/requirements.txt
            new_requirements=requirements.txt

            shopt -s dotglob
            rsync -a . $WORK_DIR

            cd $WORK_DIR
            source venv/bin/activate

            if cmp -s ${old_requirements} ${new_requirements}; then
              echo 'Tái sử dụng thư viện từ workspace cũ'
            else
              echo 'Cài đặt từ requirements.txt mới'
              pip install -r requirements.txt
            fi
            
            # Chạy ứng dụng với Gunicorn
            sudo systemctl restart semantic_search # Kiểm tra lại đường dẫn và ứng dụng

workflows:
  deploy-to-ec2:
    jobs:
      - prepare_dev:
          filters:
            branches:
              only:
                - main
